steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/featuredocs-api', '.']
    dir: 'api'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/featuredocs-api']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'featuredocs-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/featuredocs-api'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'CONTENT_DIR=/app/content,GITHUB_OWNER=glassa-work,GITHUB_REPO=featuredocs'
